
name: 'demo_dbt'
version: '1.0.0'
config-version: 2

vars:
    current_champion: Lakers


profile: 'snowflake'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

on-run-start: "{{ insert_audits('run_start') }}"
on-run-end: "{{ insert_audits('run_end') }}"

models:
  pre-hook: "{{ insert_audits('model_start') }}"
  post-hook: "{{ insert_audits('model_end') }}"
  demo_dbt:
      staging:
          +materialized: table
          +schema: staging
