name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - id: changed_files
        uses: jitterbit/get-changed-files@v1

      - name: test logic
        if: >
          [[ "${{ steps.files.outputs.added_modified  }} == "models/"*  ]] &&
          [[ "${{ steps.files.outputs.added_modified  }}" != "models/docs"* ]];
        run: |
          for changed_file in ${{ steps.files.outputs.added_modified }}; do
            if [[ "${{ steps.files.outputs.added_modified  }} == "models/"*  ]] && [[ "${{ steps.files.outputs.added_modified  }}" != "models/docs"* ]]; then
              echo "${changed_file} this file passes"
            else
              echo "${changed_file} this file does NOT pass"
          done
