name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - id: changed_files
        uses: jitterbit/get-changed-files@v1

#      - name: dbt run
#        run: echo "it worked"
#        if: >
#          [[ "${{ steps.files.outputs.all }} == "models/"*  ]] &&
#          [[ "${{ steps.files.outputs.all }}" != "models/docs"* ]];

      - name: dbt-run
        if: >
          [[ "${{ steps.files.outputs.all }} == "models/"*  ]] &&
          [[ "${{ steps.files.outputs.all }}" != "models/docs"* ]];
        uses: mwhitaker/dbt-action@master
        with:
          dbt_command: "dbt run --exclude sample_data__store_sales --profiles-dir ."
