name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - id: changed_files
        uses: jitterbit/get-changed-files@v1
      
      - id: count_models
        run: |
          cnt_models_changed=0
          for file in "${{ steps.files.outputs.added_modified[@] }}"; do
            if [[ $file == "models/"* ]] && [[ $file != "models/docs"* ]]; then
              echo $file
              let "cnt_models_changed+=1"
            fi
          done
          echo $cnt_models_changed
          echo "::set-output name=action_fruit::$cnt_models_changed"       

      - name: test logic 
        run: echo "${{ steps.count_models.outputs.action_fruit  }}"
