name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Set env
        run: echo "MODELS=$(echo git diff --name-only)" >> $GITHUB_ENV

      - name: Set env2
        run: echo "TEST=Hello" >> $GITHUB_ENV

      - name: Test
        run: echo $MODELS

      - name: Test2
        run: echo $TEST

