name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "Do something with this ${changed_file}."
          done
      
      - id: count_models
        run: |
          echo ${{ steps.files.outputs.all }}
          echo "${{ steps.files.outputs.all }}"
          cnt_models_changed=0
          for file in ${{ steps.files.outputs.all }}; do
            if [[ $file == "models/"* ]] && [[ $file != "models/docs"* ]]; then
              echo $file
              let "cnt_models_changed+=1"
            else
              echo $file
            fi
          done
          echo $cnt_models_changed
          echo "::set-output name=model_count::$cnt_models_changed"       

      - name: test logic 
        run: echo "${{ steps.count_models.outputs.model_count  }}"
