name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - id: changed_files
        uses: jitterbit/get-changed-files@v1

      - name: test logic
        if: >
          [[ "${{ steps.files.outputs.added_modified  }} == "nope/"*  ]] &&
          [[ "${{ steps.files.outputs.added_modified  }}" != "models/docs"* ]];
        run: echo "This should not run"
